<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWdhtza2\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWdhtza2/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWdhtza2.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWdhtza2\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWdhtza2\appProdProjectContainer([
    'container.build_hash' => 'Wdhtza2',
    'container.build_id' => 'fe403969',
    'container.build_time' => 1626344141,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWdhtza2');
